export const providerVisit2026 = {
  id: 'provider-visit-2026',
  name: 'Provider Visit 2026',
  shortName: 'Provider Visit',
  description: 'Cook Children\'s Health Plan — Provider Relations Visit Form',
  category: 'Provider Relations',
  color: 'blue',
  originalFile: '12550 South Fwy Ste 106.pdf',
  builtIn: true,
  sections: [
    {
      id: 'visit-info',
      title: 'Visit Information',
      questions: [
        {
          id: 'visit_types',
          type: 'multicheck',
          label: 'Type of Visit',
          hint: 'Select all that apply',
          required: true,
          options: ['Orientation', 'Education/Servicing', 'APM/PIP Reports', 'Problem Resolution'],
        },
        {
          id: 'date_of_visit',
          type: 'date',
          label: 'Date of Visit',
          required: true,
        },
        {
          id: 'provider_name',
          type: 'text',
          label: 'Provider / Group Name / Specialty',
          required: true,
          placeholder: 'e.g., Green Oaks PT Burleson — Single Specialty',
        },
        {
          id: 'address',
          type: 'text',
          label: 'Address / City / State / Zip',
          required: true,
          placeholder: 'e.g., 12550 South Fwy Ste 106, Burleson, TX 76028',
        },
        {
          id: 'group_npi_tax',
          type: 'text',
          label: 'Group NPI / Tax ID',
          required: true,
          placeholder: 'e.g., 1083923916 / 76-0551398',
        },
        {
          id: 'contact_info',
          type: 'text',
          label: 'Contact Name / Title / Contact Info',
          required: true,
          placeholder: 'e.g., Ashley Giles — agiles@usph.com',
        },
        {
          id: 'office_hours',
          type: 'text',
          label: 'Office Hours',
          required: false,
          placeholder: 'e.g., Mon–Fri 8am–5pm',
        },
        {
          id: 'lob',
          type: 'multicheck',
          label: 'Line of Business (LOB)',
          hint: 'Select all that apply',
          required: true,
          options: ['CHIP', 'CHIP Perinate', 'STAR', 'STAR KIDS'],
        },
        {
          id: 'pr_representative',
          type: 'text',
          label: 'PR Representative',
          required: true,
          placeholder: 'Enter your name',
        },
      ],
    },
    {
      id: 'items-discussed',
      title: 'Items Discussed',
      questions: [
        {
          id: 'items_discussed',
          type: 'multicheck',
          label: 'Select all items discussed during the visit',
          hint: 'Check all that apply',
          required: false,
          options: [
            'Access2Care',
            'Ask Me3',
            'CCHP Webinar Schedule',
            'CCHP Website',
            'Complaints and Appeals Process',
            'Demographic Change Form',
            'Interpreter Services',
            'Member Rights and Responsibilities',
            'PEMS',
            'Provider Manual',
            'Provider Portal',
            'Provider Relations Intro',
            'QRG',
            'VAS',
            'Recruiting',
            'Claims Issues',
            'Compliance & Quality',
            'Other',
          ],
        },
        {
          id: 'other_item',
          type: 'text',
          label: 'Other — Please specify',
          required: false,
          conditional: { field: 'items_discussed', includes: 'Other' },
        },
      ],
    },
    {
      id: 'pcp-pediatrics',
      title: 'PCP / Pediatrics',
      questions: [
        {
          id: 'pcp_items',
          type: 'multicheck',
          label: 'PCP/Pediatrics items reviewed',
          hint: 'Check all that apply',
          required: false,
          options: [
            'CHIP Perinatal Reference Guide',
            'THSteps Quick Ref Guide',
            'Periodicity Schedule Guide',
            'CHIP Well Child Education',
            'Texas Health Steps Education',
          ],
        },
      ],
    },
    {
      id: 'new-provider-orientation',
      title: 'New Provider Orientation',
      questions: [
        {
          id: 'orientation_items',
          type: 'multicheck',
          label: 'New Provider Orientation items completed',
          hint: 'Check all that apply',
          required: false,
          options: [
            'PCP Orientation',
            'Specialty, Ancillary & Facility Orientation',
            'PIP/APM: PIP Brochure',
            'Secure Provider Portal Training',
          ],
        },
      ],
    },
    {
      id: 'access-availability',
      title: 'Access and Availability Standards',
      questions: [
        {
          id: 'access_standards',
          type: 'multicheck',
          label: 'Access standards reviewed with provider',
          hint: 'Check all that apply',
          required: false,
          options: [
            'Access standards for Behavioral Health Providers',
            'Access standards for Case Management for Children and Pregnant Women Providers',
            'Access standards for LTSS Providers',
            'Access standards for OBGYN Providers',
            'Access standards for Primary Care Providers',
            'Access standards for Specialty Care Providers',
            'Access standards for Therapy Providers',
          ],
        },
      ],
    },
    {
      id: 'talking-points',
      title: 'Talking Points / Action Items',
      questions: [
        {
          id: 'talking_points',
          type: 'multicheck',
          label: 'Provider Relations Talking Points / Action Items addressed',
          hint: 'Check all that apply',
          required: false,
          options: [
            'Claims/Referrals/Authorization',
            'Support/Satisfaction/Improvements',
            'ND Demographic/Roster Updates (upcoming changes)',
            'Contracting/Credentialing',
            'Member Issues (no-shows, open panel)',
            'New Practice Manager/Office Contact',
            'Provider Education/Notifications',
            'New Credentialing Contact',
            'CCHP Dept. Support',
            'Specialty Care Gap',
            'Data Reporting',
            'Delegated Credentialing Group',
          ],
        },
        {
          id: 'specialty_care_gap_detail',
          type: 'text',
          label: 'Specialty Care Gap — Specify',
          required: false,
          conditional: { field: 'talking_points', includes: 'Specialty Care Gap' },
        },
        {
          id: 'delegated_credentialing_yn',
          type: 'radio',
          label: 'Delegated Credentialing Group — Y or N',
          required: false,
          options: ['Y', 'N'],
          conditional: { field: 'talking_points', includes: 'Delegated Credentialing Group' },
        },
        {
          id: 'delegated_credentialing_name',
          type: 'text',
          label: 'Delegated Credentialing Group Name',
          required: false,
          conditional: { field: 'talking_points', includes: 'Delegated Credentialing Group' },
        },
      ],
    },
    {
      id: 'provider-comments',
      title: 'Provider Questions / Comments / Action Items',
      questions: [
        {
          id: 'provider_comments',
          type: 'textarea',
          label: 'Provider Questions, Comments, and Action Items',
          required: false,
          placeholder: 'Enter any provider questions, comments, or action items discussed...',
        },
        {
          id: 'rep_email',
          type: 'email',
          label: 'Provider Representative Email Address',
          required: false,
          placeholder: 'e.g., representative@cookchildrens.org',
        },
      ],
    },
  ],
};
