export const siteEvaluationTool = {
  id: 'site-evaluation-tool',
  name: 'Site Evaluation Tool',
  shortName: 'Site Eval',
  description: 'Cook Children\'s Health Plan — Provider Site Evaluation Tool',
  category: 'Site Evaluation',
  color: 'teal',
  originalFile: 'Site Evaluation Tool.pdf',
  builtIn: true,
  sections: [
    {
      id: 'provider-info',
      title: 'Provider Information',
      questions: [
        { id: 'provider_name', type: 'text', label: 'Provider Name', required: true, placeholder: 'Full provider or practice name' },
        { id: 'provider_specialty', type: 'text', label: 'Provider Specialty / Type', required: true, placeholder: 'e.g., Primary Care, Physical Therapy' },
        { id: 'address', type: 'text', label: 'Address', required: true, placeholder: 'Street address' },
        { id: 'telephone', type: 'tel', label: 'Telephone Number', required: true, placeholder: 'e.g., (817) 426-4401' },
        { id: 'contact_name', type: 'text', label: 'Contact Name', required: true, placeholder: 'On-site contact person' },
        { id: 'email', type: 'email', label: 'Email Address', required: false, placeholder: 'Contact email' },
      ],
    },
    {
      id: 'accessibility',
      title: 'Accessibility',
      scoring: true,
      questions: [
        { id: 'acc_01', type: 'yes-no-na', label: 'Office name and address clearly marked and visible', pointValue: 1 },
        { id: 'acc_02', type: 'yes-no-na', label: 'Adequate parking available', pointValue: 1 },
        { id: 'acc_03', type: 'yes-no-na', label: 'Handicapped parking clearly marked', pointValue: 2 },
        { id: 'acc_04', type: 'yes-no-na', label: 'Handicapped access to the building', pointValue: 2 },
        { id: 'acc_05', type: 'yes-no-na', label: 'Waiting room is neat, clean and well maintained', pointValue: 1 },
        { id: 'acc_06', type: 'yes-no-na', label: 'Adequate seating available in waiting room', pointValue: 1 },
        { id: 'acc_07', type: 'yes-no-na', label: 'Restroom with handicap access available on each floor (at least one equipped with grab bars and is wheelchair accessible)', pointValue: 1 },
        { id: 'acc_08', type: 'yes-no-na', label: 'Restroom are clean and clearly marked', pointValue: 0 },
        { id: 'acc_09', type: 'yes-no-na', label: 'Exam rooms are clean, private and adequately sized', pointValue: 1 },
      ],
    },
    {
      id: 'appointment-availability',
      title: 'Appointment Availability / Accessibility',
      scoring: true,
      questions: [
        { id: 'appt_01', type: 'yes-no-na', label: 'Urgent Care with 24 hours of request', pointValue: 3 },
        { id: 'appt_02', type: 'yes-no-na', label: 'Routine care within 2 weeks of request', pointValue: 2 },
        { id: 'appt_03', type: 'yes-no-na', label: 'Routine specialty care within 30 Days', pointValue: 1 },
        { id: 'appt_04', type: 'yes-no-na', label: 'Non high risk prenatal care within 2 weeks of request', pointValue: 1 },
        { id: 'appt_05', type: 'yes-no-na', label: 'Preventive health services for children within 90 days of request', pointValue: 2 },
        { id: 'appt_06', type: 'yes-no-na', label: 'Preventive health services for children within 90 days at birth or within 2 weeks after birth', pointValue: 2 },
        { id: 'appt_07', type: 'yes-no-na', label: 'Patient seen within a wait time of 45 minutes or less during routine visits', pointValue: 2 },
      ],
    },
    {
      id: 'hazard-infection',
      title: 'Hazard Controls / Infection Control',
      description: 'Verified by visual inspection',
      scoring: true,
      questions: [
        { id: 'haz_01', type: 'yes-no-na', label: 'X-ray hazard signs posted', pointValue: 2 },
        { id: 'haz_02', type: 'yes-no-na', label: 'Sterilization/disinfecting method in use (heat, chemical, or disposable)', pointValue: 1 },
        { id: 'haz_03', type: 'yes-no-na', label: 'Easy access to hand wash sink/soap and hand sanitizers before and after seeing each patient', pointValue: 1 },
        { id: 'haz_04', type: 'yes-no-na', label: 'Exam rooms are adequately sized and are cleaned between patients', pointValue: 2 },
        { id: 'haz_05', type: 'yes-no-na', label: 'Hazardous waste receptacles and sharp containers used. Disposal process in place', pointValue: 2 },
        { id: 'haz_06', type: 'yes-no-na', label: 'Policy and Policy manual for disposal of hazardous material and waste', pointValue: 2 },
        { id: 'haz_07', type: 'yes-no-na', label: 'Pick up and drop off slips present for hazardous waste and material', pointValue: 2 },
        { id: 'haz_08', type: 'yes-no-na', label: 'OSHA Publication 3165 posted', pointValue: 1 },
      ],
    },
    {
      id: 'emergency-preparedness',
      title: 'Emergency Preparedness',
      description: 'Verified by visual inspection',
      scoring: true,
      questions: [
        { id: 'emg_01', type: 'yes-no-na', label: 'Smoke detector / fire alarms present and clearly identified', pointValue: 2 },
        { id: 'emg_02', type: 'yes-no-na', label: 'Fire extinguishers visible and accessible', pointValue: 2 },
        { id: 'emg_03', type: 'yes-no-na', label: 'Fire extinguishers routinely inspected', pointValue: 1 },
        { id: 'emg_04', type: 'yes-no-na', label: 'Exit signs visible', pointValue: 1 },
        { id: 'emg_05', type: 'yes-no-na', label: 'Passageways are unobstructed', pointValue: 2 },
        { id: 'emg_06', type: 'yes-no-na', label: 'Evacuation plan in place for emergencies', pointValue: 1 },
        { id: 'emg_07', type: 'yes-no-na', label: 'Instructions in place for urgent or medical emergencies', pointValue: 1 },
        { id: 'emg_08', type: 'yes-no-na', label: 'Emergency telephone numbers posted', pointValue: 1 },
        { id: 'emg_09', type: 'yes-no-na', label: 'Office staff CPR trained (at least 1 trained person on-site at all times)', pointValue: 2 },
        { id: 'emg_10', type: 'yes-no-na', label: 'Minimal acceptable emergency equipment present (ambu bag, O2, multiple sized airways)', pointValue: 2 },
      ],
    },
    {
      id: 'medical-records',
      title: 'Medical Records',
      scoring: true,
      questions: [
        { id: 'med_01', type: 'yes-no-na', label: 'Standard format used for all patient records', pointValue: 1 },
        { id: 'med_02', type: 'yes-no-na', label: 'Identifier data present on every page / medical record', pointValue: 1 },
        { id: 'med_03', type: 'yes-no-na', label: 'All papers in the record are secured to the file', pointValue: 1 },
        { id: 'med_04', type: 'yes-no-na', label: 'Medical records are kept in a secure area away from patients or outside personnel access (electronic or paper)', pointValue: 2 },
        { id: 'med_05', type: 'yes-no-na', label: 'Files are organized in a manner appropriate to the size of facility', pointValue: 1 },
        { id: 'med_06', type: 'yes-no-na', label: 'Records legible and reproducible', pointValue: 2 },
      ],
    },
    {
      id: 'patient-education',
      title: 'Patient Education / Patient Rights',
      scoring: true,
      questions: [
        { id: 'edu_01', type: 'yes-no-na', label: 'TDI complaint process and Toll free number prominently displayed in English and Spanish', pointValue: 1 },
        { id: 'edu_02', type: 'yes-no-na', label: 'Texas Medical Board complaint poster prominently displayed in English and Spanish', pointValue: 1 },
        { id: 'edu_03', type: 'yes-no-na', label: 'Procedure for patient privacy in place', pointValue: 1 },
      ],
    },
    {
      id: 'credentialing-staffing',
      title: 'Credentialing and Staffing',
      scoring: true,
      questions: [
        { id: 'cred_01', type: 'yes-no-na', label: 'Documented process for credentialing practitioners/clinic or facility', pointValue: 2 },
        { id: 'cred_02', type: 'yes-no-na', label: 'Licensures / Certifications posted and/or available for viewing', pointValue: 1 },
        { id: 'cred_03', type: 'yes-no-na', label: 'For facilities: Documented Risk Management or Quality Management review program in place', pointValue: 2 },
        { id: 'cred_04', type: 'yes-no-na', label: 'For facilities: Policy and processes in place for referral to appropriate level of care for individuals who are suicidal, homicidal, or unable to conduct activities of daily living and for transfer to a medical facility in an emergency', pointValue: 2 },
        { id: 'cred_05', type: 'yes-no-na', label: 'For facilities: Written policy and procedures for the use of seclusion or restraint', pointValue: 2 },
        { id: 'cred_06', type: 'yes-no-na', label: 'For facilities: Has an activity coordinator or programs for resident activities', pointValue: 2 },
      ],
    },
    {
      id: 'recommendation',
      title: 'Recommendation',
      questions: [
        {
          id: 'review_result',
          type: 'radio',
          label: 'Review Result',
          required: true,
          options: ['Accepted Review', 'Unaccepted Review'],
        },
        {
          id: 'revisit_date',
          type: 'date',
          label: 'Revisit Date (if unaccepted)',
          required: false,
          conditional: { field: 'review_result', equals: 'Unaccepted Review' },
        },
        {
          id: 'cchp_reviewer',
          type: 'text',
          label: 'CCHP Reviewer',
          required: true,
          placeholder: 'Reviewer full name',
        },
        {
          id: 'review_date',
          type: 'date',
          label: 'Review Date',
          required: true,
        },
        {
          id: 'office_personnel_name',
          type: 'text',
          label: 'Office Personnel Present — Print Name',
          required: false,
          placeholder: 'Name of office staff present',
        },
        {
          id: 'credentialing_committee_action',
          type: 'textarea',
          label: 'Credentialing Committee Action / Recommendation',
          required: false,
          placeholder: 'Enter any credentialing committee action or recommendation...',
        },
        {
          id: 'committee_date',
          type: 'date',
          label: 'Committee Date',
          required: false,
        },
      ],
    },
  ],
};
